services:
  nextjs:
    build:
      context: ../  # Project root as the context to include the necessary files
      dockerfile: dockerFiles/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - ../:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
